Repository Daan645/lose-your-head-the-client-case, pull requests merged in 2025-01, with the labels that each got.

#161 Verbeteren van mobile menu #71
  package-lock.json
  package.json
  src/lib/atoms/slideinmenu_link.svelte
  src/lib/atoms/tabmenu_link.svelte
  src/lib/molecules/slideinmenu.svelte
  src/lib/molecules/tabmenu.svelte
  src/lib/organism/Mobilenav.svelte
  src/lib/organism/Mobilenav2.svelte
  src/lib/organism/page.js
  src/routes/+layout.svelte
  src/routes/+page.svelte
Labels: testen

#196 Error page v2
  src/lib/homelink/Homelink.svelte
  src/lib/mainform/Mainform.svelte
  src/routes/error/+page.svelte
Labels: Refactor

#171 Weekselectie v2.0
  src/lib/molecules/WeekSelectie.svelte
  src/lib/scripts/Weekselectie/GetDates.js
Labels: documentation, Feature, component
